### ISSUE TITLE
Website download buttons broken on narrow screens

### ISSUE THREAD

**Issue by smiller171** [Alia5/GloSC#68]
If you visit the website on a mobile device or a browser window with a narrow screen, the download buttons are currently hidden. CSS below to both fix this issue and allow the download buttons to stack nicely

```css
:not(.header) + .row.center { margin-top: -20px; }
.row.center > :not(.header) { margin-top: 20px; }

\\ remove this in your existing CSS
@media only screen and (max-width: 992px)
.parallax-container .section {
    position: absolute;
    top: 40%;
}
```

## Current narrow window
![image](https://user-images.githubusercontent.com/3587913/53032166-4d3c7280-343c-11e9-9244-c8e33b9a1485.png)
## Fixed narrow window
![image](https://user-images.githubusercontent.com/3587913/53032433-d2278c00-343c-11e9-8e5c-52fdb96a7c87.png)
## Current mobile
![image](https://user-images.githubusercontent.com/3587913/53032459-e3709880-343c-11e9-9044-9174fd1e5740.png)
## Fixed Mobile
![image](https://user-images.githubusercontent.com/3587913/53032502-f4210e80-343c-11e9-9696-26d5adfd3882.png)
